# Generated by Django 4.2 on 2023-06-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='project1',
        ),
    ]
