# Generated by Django 4.2 on 2023-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_rename_project_project1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='taskrate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
