# Generated by Django 4.2 on 2023-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_alter_project1_taskrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='budget',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
