# Generated by Django 4.2 on 2023-06-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_project1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=255)),
                ('taskdes', models.CharField(max_length=255)),
                ('taskrph', models.CharField(max_length=255)),
                ('billable', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project1',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.task'),
        ),
    ]
