# Generated by Django 4.2 on 2023-06-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_task_project1_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project1',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1'),
        ),
    ]
