# Generated by Django 4.2 on 2023-06-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_remove_project1_tasks_task_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskrph',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
