# Generated by Django 4.2 on 2023-06-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_remove_userz_email_userz_proj_alter_userz_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userz',
        ),
    ]
