# Generated by Django 4.2 on 2023-06-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_rename_newuser_userz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userz',
        ),
    ]
