# Generated by Django 4.2 on 2023-06-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_userz_delete_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userz',
        ),
    ]
