# Generated by Django 4.2 on 2023-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_usernamez_emailz_usernamez_usernamez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
