# Generated by Django 4.2 on 2023-07-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_task_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='taskdesc',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='taskn',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='taskrate',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='usern',
        ),
    ]
