# Generated by Django 4.2 on 2023-07-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_remove_project1_email_remove_project1_taskdesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
