# Generated by Django 4.2 on 2023-07-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
