# Generated by Django 4.2 on 2023-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0028_project1_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.CharField(default='Inactive', max_length=255),
        ),
    ]
