# Generated by Django 4.2 on 2023-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0030_alter_project1_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='active',
            field=models.CharField(blank=True, default='Inactive', max_length=255, null=True),
        ),
    ]
