# Generated by Django 4.2 on 2023-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0031_alter_project1_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
