# Generated by Django 4.2 on 2023-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0032_alter_project1_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
