# Generated by Django 4.2 on 2023-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0033_project1_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='billable',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Not Billed', 'Not Billed')], default='Not Billed', max_length=255, null=True),
        ),
    ]
