# Generated by Django 4.2 on 2023-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0034_alter_task_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
