# Generated by Django 4.2 on 2023-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0035_customer_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
