# Generated by Django 4.2 on 2023-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0036_alter_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
